/**
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 * Class Name      : CaseController
 * Author          : <YourName>
 * Created Date    : Feb 26, 2026
 * Last Modified By: <YourName>
 * Last Modified On: Feb 26, 2026
 * Description     : This class implements for......
 *  
 * Change History  :
 *  Date          │   Author     │   Change
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 *  Feb 26, 2026  │ <YourName>   │ Initial version
 * ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 */

public class CaseController {

	@AuraEnabled(cacheable=true)
	public static void createCaseViaLwc() {
		
	}

}